# Generated by Django 4.0.4 on 2022-06-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, max_length=1024, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'airline',
                'verbose_name_plural': 'Airline',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='F-47515', max_length=7)),
                ('origin', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('trip_class', models.IntegerField(default=3)),
                ('state', models.IntegerField(default=0)),
                ('dept_date', models.DateField()),
                ('dept_time', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=404.11, max_digits=10)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline', to='airline.airline')),
            ],
            options={
                'verbose_name': 'flights',
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
