# Generated by Django 4.0.4 on 2022-06-03 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='P-29977', max_length=9)),
                ('amount', models.IntegerField()),
                ('method', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime(2022, 6, 3, 16, 53, 52, 952133))),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='airline.flights')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
